- name: check conditions for numbers
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter a number
    private: false
  tasks:
  - name: check if number is greater than 10
    ansible.builtin.debug:
     msg: "given{{number} }is greater than 10"
     when: number | > 10
  - name: checck if number is less than 10"
    ansible.builtin.debug:
     msg: "given {{number}} is less than 10" 
     when: number | < 10 