- name: variables from arguments
  hosts: localhost
  vars:
    person: aravind
    wishes: goodmorning
  tasks:
  - name: print the variables
    ansible.builtin.debug:
     msg: "hi {{person}},very {{wishes}}"